### ISSUE TITLE
Missing Check Parameters

### ISSUE THREAD

**Issue by siquylee** [max-eroshkin/InnoSetup.ScriptBuilder#5]
From Inno Setup documentation

> There is one optional parameter that is supported by all sections whose entries are separated into parameters. This is:
> 
> Check
> The name of a check function that determines whether an entry has to be processed or not. The function must either be a custom function in the [Code] section or a support function.

Currently I could not found Check member in Run/Uninstall. Do you have any plan to support this?

**Comment by max-eroshkin** [comment]
Hello! I'll check this parameter and fix it.

**Comment by max-eroshkin** [comment]
@siquylee Please check 1.0.1 package version.

**Comment by siquylee** [comment]
Thank you so much. It works like a charm.
