### ISSUE TITLE
Missing checkablealone flag for Component

### ISSUE THREAD

**Issue by siquylee** [max-eroshkin/InnoSetup.ScriptBuilder#6]
The component supports checkablealone flag but I don't see it in Enum values. Please check the documentation here https://jrsoftware.org/ishelp/index.php?topic=componentssection

**Comment by max-eroshkin** [comment]
Hello, @siquylee !
will fix it soon

**Comment by max-eroshkin** [comment]
@siquylee, please check 1.2.0 version

**Comment by siquylee** [comment]
It's so great. Thank you so much for your quick support
